# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_of_quiz',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default=django.utils.datetime_safe.date.today, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Test quiz', max_length=100),
            preserve_default=False,
        ),
    ]
