# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20180823_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
