# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('quiz', '0003_quiz_quiz_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='keystroke_test_type',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
