# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keystroke', '0002_auto_20180820_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystroketestsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
