# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180823_1628'),
        ('keystroke', '0003_auto_20180820_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeystrokeTestComparisonResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keystroke.KeystrokeTestType')),
            ],
        ),
    ]
