# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_username', models.CharField(max_length=250)),
                ('face_image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
