# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(upload_to=student.models.face_image_directory_path),
        ),
    ]
